### PR TITLE
Deprecate keyless connect() and connectFilter()

### LINKED ISSUE #340: deprecate the key-less version of Reflux.connect()
see PR #243.

using `setState` will fail without a key. Deprecate support for the "key-less" usage of `Reflux.connect()`

### PR DESCRIPTION
**Pull request by devinivy**
This is meant to resolve #340.  Figured we should get it in while making changes for 0.4.0.

### CODE REVIEW

**Comment by devinivy** [comment]
@spoike I feel fairly confident that the correct changes have been made (though of course I'd never turn down a code review!), so I'm mostly checking to make sure you sign-off on the API change.

**Comment by Asgator** [comment]
Hmm, maybe need rename pull request, for you remove feature and not reported in older versions it is outdated.

**Comment by devinivy** [comment]
@Asgator can you explain your expectation?  This will be in 0.4.0, which indicates, thanks to semantic versioning, that there are breaking changes.  We'll make release notes when 0.4.0 comes out, including any steps one would need to take to migrate from 0.3.x to 0.4.0.

**Comment by Asgator** [comment]
@devinivy okay, i agree, it's not a bad way.

**Comment by Asgator** [comment]
Maybe it's time to merge?

**Pull request merged**
