### PR TITLE
Support React 0.14

### LINKED ISSUE #424: support react 0.14
reflux not support react 0.14

### PR DESCRIPTION
**Pull request by dtinth**
This pull request:

- tweaks the build configurations so that it’s easier for third-party developers to contribute:
  - install `grunt-cli` as `devDependencies`, therefore not requiring developers to pollute their system with a globally-installed `grunt-cli`.
  - only run SauceLabs tests when `$SAUCE_USERNAME` is present. This is because SauceLabs credentials are secret, so Travis don’t put them in when building pull requests from non-collaborators.
- modifies `package.json` to allow React 0.14
- modifies the Travis build script to run tests on React 0.12, 0.13, 0.14 and make sure that all tests pass on all supported React versions.
- closes #424

### CODE REVIEW

**Comment by hrmoller** [comment]
:thumbsup:

**Comment by FredericHeem** [comment]
+1

**Comment by dtinth** [comment]
@spoike It’s green now, but I was unable to get build matrix working.

Now it only tests on React 0.14, which passes.

**Comment by svenanders** [comment]
:+1:

**Comment by spoike** [comment]
:+1: Thanks a lot, this is going to be published ASAP.

**Comment by STuFF** [comment]
:+1:

**Comment by qamil** [comment]
Thanks for your hard work @dtinth and @spoike!

**Comment by ce07c3** [comment]
Thanks!!! :+1: :+1: :+1:

**Pull request merged**
