### PR TITLE
Reflux.connectFilter: Re-filter listenable when this.props changes

### PR DESCRIPTION
**Pull request by robert-chiniquy**
This change is premised on the assumption that callers will reference `this.props` in their `filterFunc`s, and expect the component's state to reflect changes in `this.props` regardless of if the store has triggered again. I do not think the current behavior is incorrect primarily because of ambiguity in the docs, but in this example from the README:

```javascript
    mixins: [Reflux.connectFilter(postStore, "post", function(posts) {
        return posts.filter(function(post) {
           return post.id === this.props.id;
        }.bind(this))[0];
    })],
```

… The component's state will only be correct if `this.props.id` never changes. 

In the case of stores which present collections, and components using `Reflux.connectFilter` on them filtering via `this.props`, in my case `this.props.params`, the expected behavior IMO is that the component's state will update when `this.props.params` changes. 

It seemed to me that `componentWillUpdate` was the best place to locate that, but maybe `componentWillReceiveProps` is better.

I wasn't sure how to add a good test for this in the test suite.

### CODE REVIEW

**Comment by robert-chiniquy** [comment]
`componentWillReceiveProps` doesn't seem like a good fit because `nextProps` is passed as a parameter, but `this.props` is still old (so calling `filterFunc` again won't have the desired effect).

**Comment by robert-chiniquy** [comment]
Flip side, I shouldn't call `this.setState` in `componentWillUpdate` either. Not sure how to solve this problem the right way.

**Comment by robert-chiniquy** [comment]
Well, this seems important to do, but not sure how to do it without changing the interface to `Reflux.connectFilter` to take `props` as well.

**Comment by OddEssay** [comment]
Is there any further discussion on this subject anywhere else? `Reflux.connectFilter` works really nicely for my use case until I hit this exact problem and I'm now not sure how best to handle a change in `this.props`?

**Comment by robert-chiniquy** [comment]
Hi @OddEssay — There's been no other discussion of this issue. 

As you can see: https://github.com/reflux/refluxjs/pulls?q=is%3Apr+is%3Aclosed activity on Reflux has been pretty slow since this PR went unmerged, which was almost a year ago. Edges like this (this isn't the only one) are going to pop up in larger applications with Reflux, and I honestly don't think you're going to see Reflux updated to address them. Meaning no disrespect to Reflux, probably you want to move to Redux which is more active these days.

To address this with Reflux, though, you have two options.

1. Don't use `connectFilter`, just add a Reflux listener in your component and manually update the state. This will make you sad because `connectFilter` is the best part of Reflux.
2. Write a static function that takes both `props` and the store state as parameters, and returns the filtered store state. Then, call this function from both inside `connectFilter` and `componentWillReceiveProps`. <—— This is what I do in my code that still uses Reflux. It's less sad but still feels like a bit of work when theoretically I have this mixin working for me.

Hope that helps!

**Comment by OddEssay** [comment]
Thanks @robert-chiniquy - The **2** approach of creating and reusing a static function is what I'd come up with, though I'd used `listenTo` to pick up changes in the store originally, but your idea to pull down that data with `connectFilter` let me tidy that up a bit more, which I like. 👍

**Comment by robert-chiniquy** [comment]
Sure thing. Also, just thought I'd mention… You'll hit this same problem with `this.context` (or `nextContext` in `componentWillReceiveProps`), so you may want to get it out of the way and add that to your static function too.

**Pull request closed without merging**
